--liquibase formatted sql

--changeset a.khaustov:1
create table orders
(
    id       bigint primary key generated by default as identity,
    user_id bigint,
    symbol varchar(255),
    position_side varchar(255),
    type varchar(255),
    time_in_force varchar(255),
    quantity varchar(255),
    reduce_only varchar(255),
    price varchar(255),
    stop_price varchar(255),
    close_position varchar(255),
    activation_price varchar(255),
    callback_rate varchar(255),
    working_type varchar(255),
    good_till_date varchar(255),
    recw_window varchar(255),
    exchange varchar(255),
    side varchar(255),
    is_executed boolean default false,
    updated_date timestamp
);


